CreateClientConVar("chicagoRP_primary_r", 255, true, false, "Changes the (R) color value for the settings GUI's primary text.", 1, 255)
CreateClientConVar("chicagoRP_primary_g", 255, true, false, "Changes the (G) color value for the settings GUI's primary text.", 1, 255)
CreateClientConVar("chicagoRP_primary_b", 255, true, false, "Changes the (B) color value for the settings GUI's primary text.", 1, 255)
CreateClientConVar("chicagoRP_secondary_r", 130, true, false, "Changes the (R) color value for the settings GUI's secondary text.", 1, 255)
CreateClientConVar("chicagoRP_secondary_g", 25, true, false, "Changes the (G) color value for the settings GUI's secondary text.", 1, 255)
CreateClientConVar("chicagoRP_secondary_b", 40, true, false, "Changes the (B) color value for the settings GUI's secondary text.", 1, 255)
CreateClientConVar("chicagoRP_accent_r", 180, true, false, "Changes the (R) color value for the settings GUI's accent text.", 1, 255)
CreateClientConVar("chicagoRP_accent_g", 20, true, false, "Changes the (G) color value for the settings GUI's accent text.", 1, 255)
CreateClientConVar("chicagoRP_accent_b", 5, true, false, "Changes the (B) color value for the settings GUI's accent text.", 1, 255)
CreateClientConVar("chicagoRP_primarygradient_r", 230, true, false, "Changes the (R) color value for the settings GUI's primary gradient.", 1, 255)
CreateClientConVar("chicagoRP_primarygradient_g", 45, true, false, "Changes the (G) color value for the settings GUI's primary gradient.", 1, 255)
CreateClientConVar("chicagoRP_primarygradient_b", 40, true, false, "Changes the (B) color value for the settings GUI's primary gradient.", 1, 255)
CreateClientConVar("chicagoRP_secondarygradient_r", 245, true, false, "Changes the (R) color value for the settings GUI's secondary gradient.", 1, 255)
CreateClientConVar("chicagoRP_secondarygradient_g", 135, true, false, "Changes the (G) color value for the settings GUI's secondary gradient.", 1, 255)
CreateClientConVar("chicagoRP_secondarygradient_b", 70, true, false, "Changes the (B) color value for the settings GUI's secondary gradient.", 1, 255)
CreateClientConVar("chicagoRP_blur", 1, true, false, "Enables or disables UI blur when menu is active.", 0, 1)
CreateClientConVar("chicagoRP_clickpulse", 1, true, false, "Enables or disables color pulse when you click a button.", 0, 1)
CreateClientConVar("chicagoRP_dsp", 1, true, false, "Enables or disables low-pass DSP when menu is active.", 0, 1)